### ISSUE TITLE
Next.js Build Fails with Unhandled node:crypto Module Error

### ISSUE THREAD

**Issue by lostbean** [gleam-lang/crypto#13]
## Description
Build fails when running `bun run build` (Next.js 15.0.3) due to an unhandled `node:crypto` module import. The error occurs when webpack attempts to process imports from Gleam crypto modules.

## Error Message
```
Module build failed: UnhandledSchemeError: Reading from "node:crypto" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "node:" URIs.
```

## Import Trace
```
node:crypto
../core/build/dev/javascript/gleam_crypto/gleam_crypto_ffi.mjs
../core/build/dev/javascript/gleam_crypto/gleam/crypto.mjs
```

## Environment
- Next.js: 15.0.3
- Build Tool: Bun
- Project: Using Gleam crypto modules

## Possible Solution
It seems that just removing the `node:` from the protocol imports would fix it. This would allow the package to run against multiple JS engines.

**Comment by lpil** [comment]
Hello! You need to add a handler for the node protocol, as the error message says

**Comment by lostbean** [comment]
If anyone else also hits the same issue, [this](https://stackoverflow.com/a/77738096) fixed it for me
